version: '3.7'
services:
  otel4s-grafana-example:
    image: otel4s-grafana-example:0.1.0-SNAPSHOT
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-lgtm:4317"
    restart: on-failure
    ports:
      - "8080:8080"
    networks:
      - static-network

  otel-lgtm:
    image: grafana/otel-lgtm
    ports:
      - "3000:3000"
      - "4317:4317"
      - "4318:4318"
    networks:
      - static-network

networks:
  static-network:
